### ISSUE TITLE
Copy API Key to clipboard doesn't work

### ISSUE THREAD

**Issue by danutzzzzz** [javi11/altmount#6]
Clicking `copy API Key to clipboard` doesn't work

<img width="401" height="87" alt="Image" src="https://github.com/user-attachments/assets/93096260-4a11-4426-b12d-f0e91475c129" />

**Comment by danutzzzzz** [comment]
currently have to get it directly from the database.

**Comment by javi11** [comment]
Fixed

**Comment by danutzzzzz** [comment]
@javi11 the copy button still fails to work but i can now see the full API Key.. is this your planned "fix"?

**Comment by javi11** [comment]
Um can you share the browser your are using?

**Comment by danutzzzzz** [comment]
Microsoft Edge is up to date.
Version 140.0.3485.54 (Official build) (64-bit)
